### ISSUE TITLE
Enable Bitcode for target build

### ISSUE THREAD

**Issue by lecoqjacob** [pointfreeco/swift-case-paths#23] opened 2021-03-29 20:13 UTC
When building my application with bitcode enabled, it tells me the CasePath.o was built without bitcode. Was this intentional or should there be an updated release with bitcode enabled?

**Comment by stephencelis** [comment] 2021-04-15 14:59
@lecoqjacob I don't think packages set bitcode settings, so this must have to do with your project's settings downstream. We've seen similar kinds of weird downstream errors for folks that needed to modify their project's build settings, e.g.:

https://github.com/pointfreeco/swift-composable-architecture/issues/344

**Comment by stephencelis** [comment] 2021-07-05 13:52
@lecoqjacob I'm going to close this out since I think it's probably related to other build settings and not the way this package is written. If you have more to add, though, or a reproduction of a problem you think can be fixed in this repo, please let us know!

**Closed by stephencelis** 2021-07-05 13:52 UTC
Labels: question
