### ISSUE TITLE
using closure with parameters as associatedValue

### ISSUE THREAD

**Issue by dev-jko** [pointfreeco/swift-case-paths#85] opened 2022-07-04 09:53 UTC
first of all, sorry for my bad English

**Describe the bug**

when a closure with parameters is used as an associated value, parameters of extracted closure can't be received normally

**To Reproduce**

```swift
// And/or enter code that reproduces the behavior here.

func testEnumsWithParameterClosure() {
    enum Foo {
        case baz((Int) -> Void)
    }
    
    let arg = 1
    let closure: (Int) -> Void = { param in
        XCTAssertTrue(param == arg)
    }
    

    // if CasePath is not used
    guard case .baz(let extractedClosure) = Foo.baz(closure) else {
        XCTFail()
        return
    }
    extractedClosure(arg) // success


    // if CasePath is used
    guard let extracted = (/Foo.baz).extract(from: Foo.baz(closure)) else {
        XCTFail()
        return
    }
    extracted(arg) // fail
}


```

**Expected behavior**

param has the same value as arg(== 1)

**Screenshots**

**Environment**
  - swift-case-paths [0.9.0]
  - Xcode [13.4]
  - Swift [5.6]
  - OS: [iOS 15]

**Additional context**
Add any more context about the problem here.

**Comment by stephencelis** [comment] 2023-03-07 21:31
This is a known Apple bug, unfortunately, that I opened awhile ago: https://github.com/apple/swift/issues/54696

I'm going to close it out since it's not a bug we can fix in the library.

**Closed by stephencelis** 2023-03-07 21:31 UTC
Labels: apple bug
